import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { randomUUID, createHash } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';

test('real PostgreSQL migration, owner isolation, revisions, run lifecycle, reflection and deletion', async () => {
  const db = new PGlite();
  const userA = randomUUID(), userB = randomUUID(), secret = randomUUID();
  await db.exec(`create role anon; create role authenticated; create schema auth;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    grant usage on schema auth to authenticated,anon;
    grant execute on function auth.uid() to authenticated,anon;`);
  await db.query('insert into auth.users(id) values ($1),($2)', [userA,userB]);
  await db.exec(await readFile('supabase/migrations/0001_third_eye.sql','utf8'));
  await db.query("insert into private.runtime_config values ('analysis_secret_hash',$1)", [createHash('sha256').update(secret).digest('hex')]);
  const as = async (user: string) => { await db.exec('reset role'); await db.query("select set_config('request.jwt.claim.sub',$1,false)", [user]); await db.exec('set role authenticated'); };
  const rpc = async <T = any>(sql: string, params: unknown[] = []): Promise<T> => (await db.query<{ value: T }>(`select to_jsonb(${sql}) as value`, params)).rows[0].value;
  await as(userA);
  const d = await rpc('public.create_decision($1::jsonb)', [JSON.stringify({ decision: 'Choose a course?', context: 'I work during the day.' })]);
  assert.equal(d.user_id,userA); assert.equal(d.revision,1);
  await assert.rejects(() => db.query('update public.decisions set user_id=$1 where id=$2',[userB,d.id]), /permission denied/);
  await as(userB);
  assert.equal((await db.query('select * from public.decisions')).rows.length,0);
  await assert.rejects(() => rpc('public.delete_decision($1)', [d.id]), /NOT_FOUND/);
  await assert.rejects(() => rpc('public.update_decision($1,1,$2::jsonb)', [d.id, JSON.stringify({ decision:'overwrite',context:'bad' })]), /NOT_FOUND/);
  await as(userA);
  await assert.rejects(() => rpc('public.update_decision($1,5,$2::jsonb)', [d.id,JSON.stringify({ decision:'changed',context:'context' })]), /REVISION_CONFLICT/);
  const key = randomUUID();
  await assert.rejects(() => rpc('public.begin_analysis($1,1,$2,$3,45000,12)', [d.id,key,'wrong-secret']), /SERVER_CREDENTIAL/);
  const run = await rpc('public.begin_analysis($1,1,$2,$3,45000,12)', [d.id,key,secret]);
  assert.equal(run.analysis.input_snapshot.context,d.context);
  const replay = await rpc('public.begin_analysis($1,1,$2,$3,45000,12)', [d.id,key,secret]); assert.equal(replay.replay,true); assert.equal(replay.analysis.id,run.analysis.id);
  await assert.rejects(() => rpc('public.begin_analysis($1,2,$2,$3,45000,12)', [d.id,key,secret]), /IDEMPOTENCY_CONFLICT/);
  const active = await rpc('public.begin_analysis($1,1,$2,$3,45000,12)', [d.id,randomUUID(),secret]); assert.equal(active.active,true);
  await assert.rejects(() => db.query("update public.analyses set status='completed' where id=$1", [run.analysis.id]), /permission denied/);
  const questions = [{ id:'q1',path:'reflection.unansweredQuestions.0',text:'Which hours are available?' }];
  const source = { id:randomUUID(),title:'Course',url:'https://example.org/course',excerpt:'Course information',retrieved_at:new Date().toISOString() };
  const finished = await rpc("public.finish_analysis($1,$2,$3::jsonb,$4::jsonb,$5::jsonb,'test','fixture','completed',null)", [run.analysis.id,secret,JSON.stringify({ summary:{} }),JSON.stringify(questions),JSON.stringify([source])]);
  assert.equal(finished.status,'completed');
  const unchanged = await rpc("public.finish_analysis($1,$2,null,'[]','[]',null,null,'failed','LATE_FAILURE')", [run.analysis.id,secret]); assert.equal(unchanged.status,'completed');
  await assert.rejects(() => rpc("public.save_reflection($1,$2,'q2','An answer',1)",[d.id,run.analysis.id]), /INVALID_QUESTION/);
  const answer = await rpc("public.save_reflection($1,$2,'q1','Evenings',1)",[d.id,run.analysis.id]); assert.equal(answer.decisionRevision,2);
  await assert.rejects(() => rpc("public.save_reflection($1,$2,'q1','Mornings',1)",[d.id,run.analysis.id]), /REVISION_CONFLICT/);
  const second = await rpc('public.begin_analysis($1,2,$2,$3,45000,12)',[d.id,randomUUID(),secret]); assert.equal(second.analysis.input_snapshot.reflections[0].answer,'Evenings');
  await db.exec('reset role'); await db.query("update public.analyses set expires_at=now()-interval '1 second' where id=$1",[second.analysis.id]); await as(userA);
  await rpc('public.expire_runs()');
  assert.equal((await db.query<{ status: string }>('select status from public.analyses where id=$1',[second.analysis.id])).rows[0].status,'failed');
  await as(userB);
  for (const table of ['analyses','sources','reflections']) assert.equal((await db.query(`select * from public.${table}`)).rows.length,0);
  await assert.rejects(() => rpc("public.save_reflection($1,$2,'q1','attack',2)",[d.id,run.analysis.id]), /NOT_FOUND/);
  await as(userA); await rpc('public.delete_decision($1)',[d.id]);
  for (const table of ['decisions','analyses','sources','reflections']) assert.equal((await db.query(`select * from public.${table}`)).rows.length,0);
  await db.close();
});
